<template>
    <div>
        <div>
            Razão Social:
            <input/>
        </div>
        <div>
            CNPJ
            <input/>
        </div>
        <hr>
        <div>
            Endereço:
            <input/>
        </div>
        <div>
            Numero:
            <input/>
        </div>
        <div>
            Complemento:
            <input/>
        </div>
        <div>
            Bairro:
            <input/>
        </div>
        <div>
            Complemento:
            <input/>
        </div>
        <div>
            CEP:
            <input/>
        </div>
        <div>
            Telefone:
            <input/>
        </div>
        <div>
            E-mail:
            <input/>
        </div>
        <hr>
        <div>
            Responsável:
            <input/>
        </div>
        <div>
            CPF:
            <input/>
        </div>
    </div>
</template>